name: data_download_env

channels:
  - conda-forge
  - defaults
dependencies:
  - astropy=5.1
  - bs4=4.11.1
  - cdflib=0.4.7
  - netcdf4=1.5.6
  - numpy=1.23.1
  - pandas=1.4.3
  - python=3.8.10
  - requests=2.28.1